// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_records.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/maxweisen/otto/backend/internal/money"
)

const createMaintenanceRecord = `-- name: CreateMaintenanceRecord :one
INSERT INTO maintenance_records (
  vehicle_id, type, description, performed_at, mileage, cost, notes
)
SELECT v.id, $1, $2, $3, $4, $5, $6
FROM vehicles v
WHERE v.id = $7 AND v.user_id = $8
RETURNING id, vehicle_id, type, description, performed_at, mileage, cost, notes, created_at
`

type CreateMaintenanceRecordParams struct {
	Type        string        `json:"type"`
	Description string        `json:"description"`
	PerformedAt pgtype.Date   `json:"performed_at"`
	Mileage     *int32        `json:"mileage"`
	Cost        *money.Amount `json:"cost"`
	Notes       *string       `json:"notes"`
	VehicleID   int64         `json:"vehicle_id"`
	UserID      int64         `json:"user_id"`
}

func (q *Queries) CreateMaintenanceRecord(ctx context.Context, arg CreateMaintenanceRecordParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, createMaintenanceRecord,
		arg.Type,
		arg.Description,
		arg.PerformedAt,
		arg.Mileage,
		arg.Cost,
		arg.Notes,
		arg.VehicleID,
		arg.UserID,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Type,
		&i.Description,
		&i.PerformedAt,
		&i.Mileage,
		&i.Cost,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMaintenanceRecord = `-- name: DeleteMaintenanceRecord :execrows
DELETE FROM maintenance_records m
USING vehicles v
WHERE m.id = $1 AND m.vehicle_id = $2
  AND v.id = m.vehicle_id AND v.user_id = $3
`

type DeleteMaintenanceRecordParams struct {
	ID        int64 `json:"id"`
	VehicleID int64 `json:"vehicle_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) DeleteMaintenanceRecord(ctx context.Context, arg DeleteMaintenanceRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMaintenanceRecord, arg.ID, arg.VehicleID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMaintenanceRecord = `-- name: GetMaintenanceRecord :one
SELECT m.id, m.vehicle_id, m.type, m.description, m.performed_at, m.mileage, m.cost, m.notes, m.created_at
FROM maintenance_records m
JOIN vehicles v ON v.id = m.vehicle_id
WHERE m.id = $1 AND m.vehicle_id = $2 AND v.user_id = $3
`

type GetMaintenanceRecordParams struct {
	ID        int64 `json:"id"`
	VehicleID int64 `json:"vehicle_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetMaintenanceRecord(ctx context.Context, arg GetMaintenanceRecordParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, getMaintenanceRecord, arg.ID, arg.VehicleID, arg.UserID)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Type,
		&i.Description,
		&i.PerformedAt,
		&i.Mileage,
		&i.Cost,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listMaintenanceRecordsByVehicle = `-- name: ListMaintenanceRecordsByVehicle :many
SELECT m.id, m.vehicle_id, m.type, m.description, m.performed_at, m.mileage, m.cost, m.notes, m.created_at
FROM maintenance_records m
JOIN vehicles v ON v.id = m.vehicle_id
WHERE m.vehicle_id = $1 AND v.user_id = $2
ORDER BY m.performed_at DESC, m.id DESC
`

type ListMaintenanceRecordsByVehicleParams struct {
	VehicleID int64 `json:"vehicle_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) ListMaintenanceRecordsByVehicle(ctx context.Context, arg ListMaintenanceRecordsByVehicleParams) ([]MaintenanceRecord, error) {
	rows, err := q.db.Query(ctx, listMaintenanceRecordsByVehicle, arg.VehicleID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceRecord{}
	for rows.Next() {
		var i MaintenanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Type,
			&i.Description,
			&i.PerformedAt,
			&i.Mileage,
			&i.Cost,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenanceRecord = `-- name: UpdateMaintenanceRecord :one
UPDATE maintenance_records m
SET type = $1, description = $2, performed_at = $3,
  mileage = $4, cost = $5, notes = $6
FROM vehicles v
WHERE m.id = $7 AND m.vehicle_id = $8
  AND v.id = m.vehicle_id AND v.user_id = $9
RETURNING m.id, m.vehicle_id, m.type, m.description, m.performed_at, m.mileage, m.cost, m.notes, m.created_at
`

type UpdateMaintenanceRecordParams struct {
	Type        string        `json:"type"`
	Description string        `json:"description"`
	PerformedAt pgtype.Date   `json:"performed_at"`
	Mileage     *int32        `json:"mileage"`
	Cost        *money.Amount `json:"cost"`
	Notes       *string       `json:"notes"`
	ID          int64         `json:"id"`
	VehicleID   int64         `json:"vehicle_id"`
	UserID      int64         `json:"user_id"`
}

func (q *Queries) UpdateMaintenanceRecord(ctx context.Context, arg UpdateMaintenanceRecordParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceRecord,
		arg.Type,
		arg.Description,
		arg.PerformedAt,
		arg.Mileage,
		arg.Cost,
		arg.Notes,
		arg.ID,
		arg.VehicleID,
		arg.UserID,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Type,
		&i.Description,
		&i.PerformedAt,
		&i.Mileage,
		&i.Cost,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
