// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/maxweisen/otto/backend/internal/money"
)

type MaintenanceRecord struct {
	ID          int64              `json:"id"`
	VehicleID   int64              `json:"vehicle_id"`
	Type        string             `json:"type"`
	Description string             `json:"description"`
	PerformedAt pgtype.Date        `json:"performed_at"`
	Mileage     *int32             `json:"mileage"`
	Cost        *money.Amount      `json:"cost"`
	Notes       *string            `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"-"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	GoogleSub string             `json:"google_sub"`
	Email     string             `json:"email"`
	Name      *string            `json:"name"`
	AvatarUrl *string            `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Vehicle struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Year      int16              `json:"year"`
	Make      string             `json:"make"`
	Model     string             `json:"model"`
	Trim      *string            `json:"trim"`
	Vin       *string            `json:"vin"`
	Nickname  *string            `json:"nickname"`
	Mileage   *int32             `json:"mileage"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
