// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package store

import (
	"context"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
  user_id, year, make, model, trim, vin, nickname, mileage
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, year, make, model, trim, vin, nickname, mileage, created_at
`

type CreateVehicleParams struct {
	UserID   int64   `json:"user_id"`
	Year     int16   `json:"year"`
	Make     string  `json:"make"`
	Model    string  `json:"model"`
	Trim     *string `json:"trim"`
	Vin      *string `json:"vin"`
	Nickname *string `json:"nickname"`
	Mileage  *int32  `json:"mileage"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.UserID,
		arg.Year,
		arg.Make,
		arg.Model,
		arg.Trim,
		arg.Vin,
		arg.Nickname,
		arg.Mileage,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Make,
		&i.Model,
		&i.Trim,
		&i.Vin,
		&i.Nickname,
		&i.Mileage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :execrows
DELETE FROM vehicles WHERE id = $1 AND user_id = $2
`

type DeleteVehicleParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVehicle, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, user_id, year, make, model, trim, vin, nickname, mileage, created_at FROM vehicles WHERE id = $1 AND user_id = $2
`

type GetVehicleParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetVehicle(ctx context.Context, arg GetVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, arg.ID, arg.UserID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Make,
		&i.Model,
		&i.Trim,
		&i.Vin,
		&i.Nickname,
		&i.Mileage,
		&i.CreatedAt,
	)
	return i, err
}

const listVehiclesByUser = `-- name: ListVehiclesByUser :many
SELECT id, user_id, year, make, model, trim, vin, nickname, mileage, created_at FROM vehicles WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVehiclesByUser(ctx context.Context, userID int64) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Year,
			&i.Make,
			&i.Model,
			&i.Trim,
			&i.Vin,
			&i.Nickname,
			&i.Mileage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET year = $1, make = $2, model = $3, trim = $4, vin = $5, nickname = $6, mileage = $7
WHERE id = $8 AND user_id = $9
RETURNING id, user_id, year, make, model, trim, vin, nickname, mileage, created_at
`

type UpdateVehicleParams struct {
	Year     int16   `json:"year"`
	Make     string  `json:"make"`
	Model    string  `json:"model"`
	Trim     *string `json:"trim"`
	Vin      *string `json:"vin"`
	Nickname *string `json:"nickname"`
	Mileage  *int32  `json:"mileage"`
	ID       int64   `json:"id"`
	UserID   int64   `json:"user_id"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.Year,
		arg.Make,
		arg.Model,
		arg.Trim,
		arg.Vin,
		arg.Nickname,
		arg.Mileage,
		arg.ID,
		arg.UserID,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Make,
		&i.Model,
		&i.Trim,
		&i.Vin,
		&i.Nickname,
		&i.Mileage,
		&i.CreatedAt,
	)
	return i, err
}
